import { ApolloServer } from '@apollo/server'
import { makeExecutableSchema } from '@graphql-tools/schema'
import { startStandaloneServer } from '@apollo/server/standalone'
import models from './models'
import { $server } from '../config'
